### ISSUE TITLE
Bug 2

### ISSUE THREAD

**Issue by DogancanYr** [Altansar69/CS.RIN.RU-Enhanced-external#8] opened 2024-01-10 12:10 UTC
Different topic title.
https://store.steampowered.com/app/440000/Portal_2_Community_Edition/
https://cs.rin.ru/forum/viewtopic.php?f=10&t=131898

**Comment by SubZeroPL** [comment] 2024-01-10 12:20
Looks like the script appends text "Cracked easily" when there are no other tags after topic title. I'm not sure if it's correct behavior because there can be games that are not cracked but does not have a tag (especially new ones).

**Comment by Altansar69** [comment] 2024-01-10 12:30
Yes, it's true, I really didn't know what to write instead, and that's the case for most games that don't have anything written down, that's why...

**Comment by Altansar69** [comment] 2024-01-10 12:32
concerning the @dogan bug, it's "normal". It's the same bug as the first issue.
![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/a2b6672b-95ae-42e9-be8f-2c5a170a34d0)
For anything with this square, the script currently does not work

**Comment by SubZeroPL** [comment] 2024-01-11 13:14
It's not really a duplicate of #5 because in #5 the problem is with searching of the topic on rin, and here the problem is that the tag added to game name on Steam/SteamDB ("Cracked easily") is not the same as tag present on rin (no tag at all).
At the moment I can see two possible solutions to this:
1. remove this "Cracked easily" tag from Steam/SteamDB (as it can be misleading in some cases)
2. explain this behavior in Readme

Personally I'd opt for 1.

**Comment by Altansar69** [comment] 2024-01-11 14:06
Leave the Cracked easily written part 😢

**Closed** 2024-01-13 10:06 UTC
Labels: bug
